# specify the node base image with your desired version node:<version>
# 원하는 버전 node:<version>으로 노드 기본 이미지를 지정합니다.
FROM node:16

# replace this with your application's default port
# 이것을 애플리케이션의 기본 포트로 바꾸십시오.
EXPOSE 8888